name: Firebase Hosting Deploy and Cleanup

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: kotatsu-neko-429207

  cleanup:
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Authenticate to Firebase
        run: firebase auth:ci --token ${{ secrets.FIREBASE_CI_TOKEN }}
      - name: Delete preview channel
        run: firebase hosting:channel:delete preview --project kotatsu-neko-429207 --force
